### ISSUE TITLE
リンク先を更新する

### ISSUE THREAD

**Issue by ryo-gk** [french-fried-typhoon/got-gacha#10]
・「結果をシェア」に含まれるURLを「http://got.sintokyo.world/」に変更
・フッターの「戯的商店」を「sintokyo.world」に変更しリンク先を「http://sintokyo.world/」に変更

**Comment by kiaking** [comment]
これは完了、かな？

**Comment by ryo-gk** [comment]
完了です！deployありがとうございました 🙏
